"""Q4 Hidato episode driver + per-episode metrics.

A Q4 rollout is: starting from a viable root state, alternately
  policy_method.choose_action(grid) -> action_or_terminate
  env.step(grid, action) -> next_grid
until one of:
  - goal reached (Pass@1 = 1)
  - max_steps exceeded
  - method returned TERMINATE (CVCP only)
  - method failed to choose a legal action

Metrics tracked per episode (paper Table 4):
  pass_at_1            — solved (bool)
  de_entered           — at any step did the executed action lead to v(s_{t+1}) = 0
  first_de_step        — t at which DE was first entered, or None
  non_viable_selected  — count of steps where executed action was non-viable
  policy_tokens        — total tokens generated by π_θ during sampling
  eval_tokens          — total tokens generated by f_φ / scorer during evaluation
  steps_taken          — number of executed actions
  terminated           — True if method emitted TERMINATE
  fail_reason          — None / 'illegal_action' / 'no_action' / 'terminate' / 'max_steps'

NetCompute = (PolicyTokens + K * EvalTokens) / PolicyTokens_top1   (paper §3.5)
We collect the raw token counts here; the aggregator divides by Top-1's
PolicyTokens at report time.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Dict, Any

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))  # for sudoku4_env, sudoku4_solver

from hidato5x4_env import (  # noqa: E402
    apply_action,
    is_local_valid,
    is_goal,
    render_state_hidato,
    enumerate_legal_actions,
    ActionStruct,
)
from hidato5x4_solver import Hidato5x4Solver  # noqa: E402


@dataclass
class EpisodeResult:
    pass_at_1: bool = False
    de_entered: bool = False
    first_de_step: Optional[int] = None
    non_viable_selected: int = 0
    policy_tokens: int = 0
    eval_tokens: int = 0
    steps_taken: int = 0
    terminated: bool = False
    terminated_state_viable: Optional[bool] = None  # oracle viability at termination
    fail_reason: Optional[str] = None
    final_grid: Optional[List[List[int]]] = None
    action_log: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self):
        return {
            "pass_at_1": self.pass_at_1,
            "de_entered": self.de_entered,
            "first_de_step": self.first_de_step,
            "non_viable_selected": self.non_viable_selected,
            "policy_tokens": self.policy_tokens,
            "eval_tokens": self.eval_tokens,
            "steps_taken": self.steps_taken,
            "terminated": self.terminated,
            "terminated_state_viable": self.terminated_state_viable,
            "fail_reason": self.fail_reason,
        }


@dataclass
class ChoiceResult:
    """What a Method.choose_action() returns at one decision step."""
    action: Optional[ActionStruct]    # None if terminate
    terminate: bool = False
    policy_tokens: int = 0
    eval_tokens: int = 0
    info: Dict[str, Any] = field(default_factory=dict)


class Episode:
    """Drive one rollout from a starting grid using a Method.

    Paper convention: when a method picks an illegal action (locally invalid),
    the rollout fails at that step. When the executed action leads to a
    non-viable next state, we record DE entry but CONTINUE — the policy may
    still stumble through. (We never have empty action space because Sudoku
    4×4 always allows at least one local placement until the grid is complete.)
    """

    def __init__(self, solver: Hidato5x4Solver, max_steps: int = 25):
        self.solver = solver
        self.max_steps = max_steps

    def run(self, root_grid, method) -> EpisodeResult:
        # For Hidato, root_grid is actually a state DICT (rows, cols,
        # assignment, puzzle_id). Deep-copy assignment to avoid mutating caller.
        import copy
        g = copy.deepcopy(root_grid)
        result = EpisodeResult()
        for t in range(self.max_steps):
            if is_goal(g):
                result.pass_at_1 = True
                result.fail_reason = None
                break
            # If grid has empty cells but no legal action exists, we're stuck
            if not enumerate_legal_actions(g):
                result.fail_reason = "no_legal_actions"
                break

            choice = method.choose_action(g)
            result.policy_tokens += choice.policy_tokens
            result.eval_tokens += choice.eval_tokens

            if choice.terminate:
                result.terminated = True
                result.terminated_state_viable = self.solver.is_viable(g)
                result.fail_reason = "terminate"
                break

            action = choice.action
            if action is None:
                result.fail_reason = "no_action"
                break
            if not is_local_valid(g, action):
                result.fail_reason = "illegal_action"
                result.action_log.append({"step": t, "action": str(action), "illegal": True})
                break

            # Check oracle viability of THIS action *before* committing — useful for DE
            # diagnostic. We do this by computing next grid + checking solver.
            next_g = apply_action(g, action)
            next_viable = self.solver.is_viable(next_g)
            if not next_viable:
                result.non_viable_selected += 1
                if not result.de_entered:
                    result.de_entered = True
                    result.first_de_step = t
            result.action_log.append({
                "step": t, "action": str(action), "next_viable": next_viable,
            })
            g = next_g
            result.steps_taken = t + 1

        else:
            # exhausted max_steps without break
            if not is_goal(g):
                result.fail_reason = "max_steps"

        result.final_grid = g
        return result
