"""Solution-path SFT data augmenter for Polyomino tiling envs.

The motivation (see doc/sft_data_options_2026-05-01.md): SFT data generated by
random/LLM-policy play on Pentomino-easy is dominated by step-0 samples (80.7%
on B-7, 0% step-3 samples) because most rollouts terminate at step 1 due to the
predictive gap. This means the model has near-zero training signal for late-stage
states, even though those are exactly where Pass@1 = 0% manifests.

This augmenter fixes the late-stage scarcity directly:
  1. Enumerate every valid tiling of the (board, piece_set) configuration via
     backtracking + the env's DLX solvability checker.
  2. For each tiling, simulate stepping a real PolyominoEnv through the
     placement sequence, producing one TrajectoryStep per intermediate state.
  3. Format via the existing SFTFormatter so output is bit-for-bit compatible
     with the existing data pipeline.
  4. Save as parquet with the same columns as the random/LLM-policy datasets,
     so it can be concatenated with existing data.

Output: every sample has `is_solvable=True`, `is_breaking_point=False`, and
covers trajectory positions 0 through N-1 *uniformly* (one sample per piece
per tiling).

For 5×4 / 4-piece: 20 tilings × 4 pieces = 80 augmented samples.
For 5×10 / 10-piece (B-9): 4664 × 10 = 46,640 augmented samples.

Usage:
  python -m src.data.solution_path_augmenter \\
      --board-h 5 --board-w 4 --piece-set L,P,W,Y \\
      --output-dir data/pentomino_easy_solution_paths
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Iterable

import pandas as pd

# Repo path for src.* imports (when invoked as a script)
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from src.environments.polyomino import PolyominoEnv  # noqa: E402
from src.environments.polyomino_utils import PIECE_ORIENTATIONS  # noqa: E402
from src.data.trajectory_generator import (  # noqa: E402
    TrajectoryStep, TrajectoryMetadata, trajectory_to_dict,
)
from src.data.sft_formatter import SFTFormatter  # noqa: E402


# ----------------------------------------------------------------------------
# Tiling enumerator — yield (piece_letter, orientation_id, row, col) sequences
#
# Uses backtracking on row-major first-empty-cell with all (piece, ori) options.
# Same algorithm as scripts/p0_count_pentomino_tilings.py, but yields sequences
# instead of counting.
# ----------------------------------------------------------------------------

def _first_empty(board, h, w):
    for r in range(h):
        for c in range(w):
            if board[r][c] == 0:
                return (r, c)
    return None


def enumerate_tilings(board_h: int, board_w: int, piece_set: tuple) -> Iterable[list]:
    """Yield each valid tiling of board_h × board_w using `piece_set` exactly once.

    Each yielded item is a list of (piece_letter, orientation_id, row_0idx, col_0idx)
    tuples in placement order (which is row-major-first-empty-cell deterministic).
    """
    if 5 * len(piece_set) != board_h * board_w:
        return
    board = [[0] * board_w for _ in range(board_h)]
    placements = []
    yield from _backtrack_yield(board, board_h, board_w, list(piece_set), placements)


def _backtrack_yield(board, h, w, remaining, placements):
    if not remaining:
        # All pieces placed — board must be full because area matches
        yield list(placements)
        return
    pos = _first_empty(board, h, w)
    if pos is None:
        return
    r, c = pos
    for i, piece in enumerate(remaining):
        for ori_id, ori_cells in enumerate(PIECE_ORIENTATIONS[piece]):
            anchor = min(ori_cells)
            dr, dc = r - anchor[0], c - anchor[1]
            cells = [(rr + dr, cc + dc) for rr, cc in ori_cells]
            valid = True
            for ar, ac in cells:
                if not (0 <= ar < h and 0 <= ac < w):
                    valid = False; break
                if board[ar][ac] != 0:
                    valid = False; break
            if not valid:
                continue
            # The anchor of this placement (top-most leftmost cell of the piece's
            # footprint) — guaranteed to be (r, c) because we filled the FIRST
            # empty cell, so the anchor *is* (r, c).
            anchor_r, anchor_c = r, c
            for ar, ac in cells:
                board[ar][ac] = i + 1
            placements.append((piece, ori_id, anchor_r, anchor_c))
            yield from _backtrack_yield(board, h, w,
                                         remaining[:i] + remaining[i+1:],
                                         placements)
            placements.pop()
            for ar, ac in cells:
                board[ar][ac] = 0


# ----------------------------------------------------------------------------
# Trajectory generation: walk one tiling through a real PolyominoEnv
# ----------------------------------------------------------------------------

def tiling_to_trajectory(env: PolyominoEnv, tiling: list) -> tuple:
    """Step the env through a known-valid placement sequence.

    Returns (steps, metadata). Each TrajectoryStep records state, action,
    next_state, is_solvable=True for all but the final step (which is
    is_solvable irrelevant since the puzzle is solved).
    """
    state = env.reset()
    steps: list[TrajectoryStep] = []
    n = len(tiling)
    for i, (piece, ori_id, r0, c0) in enumerate(tiling):
        # Action format expected by env.step (1-indexed for rendering)
        action_str = f"place {piece} ori={ori_id} at row {r0 + 1} col {c0 + 1}"
        next_state, reward, done, info = env.step(action_str)
        if not info.get("action_is_valid", False):
            raise RuntimeError(
                f"Tiling enumeration produced an invalid action at step {i}: {action_str}\n"
                f"  feedback: {env.last_action_feedback}"
            )
        # All solution-path samples have is_solvable=True except possibly the final
        # one (which is solved=True). Treat the final state as is_solvable=True
        # since it represents a complete tiling, not doom.
        is_solvable = bool(info.get("is_solvable", True)) or info.get("success", False)
        steps_left = (n - 1) - i  # 0 on the final step

        step = TrajectoryStep(
            state=state,
            action=i,                              # placeholder (we use action_name)
            action_name=info.get("action_name", action_str),
            next_state=next_state,
            reward=reward,
            step=i,
            done_label=1 if (i == n - 1) else 0,
            steps_left=steps_left,
            steps_left_bucket=_bucket(steps_left),
            is_solvable=is_solvable,
            is_breaking_point=False,
            deadlock_type=None,
            steps_since_break=None,
            success=info.get("success", False),
        )
        steps.append(step)
        state = next_state

    metadata = TrajectoryMetadata(
        total_steps=n,
        success=True,
        has_breaking_point=False,
        breaking_point_step=None,
        steps_wasted=0,
        final_reward=1.0,
        termination_reason="success",
    )
    return steps, metadata


def _bucket(delta: int) -> str:
    if delta == 0:
        return "immediate"
    if delta <= 3:
        return "near"
    if delta <= 7:
        return "medium"
    return "far"


# ----------------------------------------------------------------------------
# Build SFT dataset rows from solution-path trajectories
# ----------------------------------------------------------------------------

def build_sft_rows(trajectories, formatter: SFTFormatter) -> list[dict]:
    """Convert a list of (steps, metadata) into SFTFormatter-formatted rows
    matching the existing parquet schema (data_source, prompt, response,
    ability, reward_model, extra_info).
    """
    # Use the same path the random/LLM-policy generator takes: SFTFormatter
    # turns a list of (trajectory, metadata) pairs into a DataFrame with the
    # right columns. We just hand it the solution-path trajectories.
    df = formatter.create_sft_dataset(trajectories)
    # Ensure consistent dtypes — extra_info may need json-encoding to match
    # the existing files (random/LLM-policy generator stores it as string).
    if "extra_info" in df.columns:
        df["extra_info"] = df["extra_info"].apply(
            lambda v: v if isinstance(v, str) else json.dumps(v, default=str)
        )
    return df.to_dict("records")


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--board-h", type=int, default=5)
    p.add_argument("--board-w", type=int, default=4)
    p.add_argument("--piece-set", default="L,P,W,Y",
                   help="Comma-separated piece letters (each used once).")
    p.add_argument("--variant", default="polyomino_minimal",
                   help="SFTFormatter variant.")
    p.add_argument("--output-dir", required=True)
    p.add_argument("--max-tilings", type=int, default=None,
                   help="Cap on number of tilings to emit (None = all).")
    p.add_argument("--repeat", type=int, default=1,
                   help="Repeat the same solution-path samples this many times "
                        "(simple oversample to balance against larger doom datasets).")
    p.add_argument("--val-frac", type=float, default=0.1,
                   help="Fraction of tilings held out for val.")
    args = p.parse_args()

    piece_set = tuple(s.strip().upper() for s in args.piece_set.split(","))
    print(f"=== solution_path_augmenter ===")
    print(f"  board:      {args.board_h}×{args.board_w} ({args.board_h * args.board_w} cells)")
    print(f"  piece set:  {piece_set} ({len(piece_set)} pieces × 5 = {5 * len(piece_set)} cells)")
    print(f"  variant:    {args.variant}")
    print(f"  repeat:     {args.repeat}")
    print(f"  val_frac:   {args.val_frac}")

    if 5 * len(piece_set) != args.board_h * args.board_w:
        raise ValueError(
            f"Cell count mismatch: board has {args.board_h * args.board_w} cells "
            f"but piece set covers {5 * len(piece_set)} cells. Cannot exact-cover."
        )

    print(f"\nEnumerating tilings...")
    tilings = []
    for tiling in enumerate_tilings(args.board_h, args.board_w, piece_set):
        tilings.append(tiling)
        if args.max_tilings is not None and len(tilings) >= args.max_tilings:
            break
    print(f"  found {len(tilings)} valid tilings")

    if not tilings:
        raise RuntimeError("No valid tilings — check piece set and board dimensions.")

    # Step each tiling through a fresh env to produce TrajectoryStep sequences
    print(f"\nWalking each tiling through PolyominoEnv...")
    env = PolyominoEnv(board_h=args.board_h, board_w=args.board_w,
                       piece_set=piece_set, max_steps=2 * len(piece_set))
    trajectories = []
    for tiling in tilings:
        steps, meta = tiling_to_trajectory(env, tiling)
        trajectories.append((steps, meta))

    # Train/val split — at TILING granularity, not step granularity, so a single
    # solution path doesn't get split across train and val.
    n_val = max(1, int(args.val_frac * len(trajectories)))
    val_trajs = trajectories[:n_val]
    train_trajs = trajectories[n_val:]
    print(f"  train tilings: {len(train_trajs)}, val tilings: {len(val_trajs)}")

    # Apply --repeat by duplicating the trajectory list
    if args.repeat > 1:
        train_trajs = train_trajs * args.repeat
        val_trajs = val_trajs * args.repeat
        print(f"  after repeat × {args.repeat}: train={len(train_trajs)}, val={len(val_trajs)}")

    # Format via SFTFormatter
    print(f"\nFormatting samples via SFTFormatter(variant={args.variant!r})...")
    formatter = SFTFormatter(variant=args.variant)
    train_rows = build_sft_rows(train_trajs, formatter)
    val_rows = build_sft_rows(val_trajs, formatter)
    print(f"  train rows: {len(train_rows)}, val rows: {len(val_rows)}")

    # Save
    os.makedirs(args.output_dir, exist_ok=True)
    train_path = os.path.join(args.output_dir, "wm_train_solution_paths.parquet")
    val_path = os.path.join(args.output_dir, "wm_val_solution_paths.parquet")
    pd.DataFrame(train_rows).to_parquet(train_path, index=False)
    pd.DataFrame(val_rows).to_parquet(val_path, index=False)
    print(f"\nWrote:")
    print(f"  {train_path}")
    print(f"  {val_path}")

    # Quick step-distribution print (verifies uniform coverage)
    all_steps = [r["extra_info"] for r in train_rows]
    if all_steps and isinstance(all_steps[0], str):
        all_steps = [json.loads(s) for s in all_steps]
    from collections import Counter
    step_counts = Counter(s.get("step") for s in all_steps)
    print(f"\nTrain trajectory-position distribution:")
    for k in sorted(step_counts):
        print(f"  step {k}: {step_counts[k]} samples")


if __name__ == "__main__":
    main()
